name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set Node.js 20.11.0
        uses: actions/setup-node@main
        with:
          node-version: 20.11.0
      - name: Install dependencies
        run: npm i
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
